### PR TITLE
Use https for local development; Update readme

### PR DESCRIPTION
**Pull request by ujovlado**
Related to #1429 

Proposed changes:

- remove `start-https` commnand
- use `--https` flag in standard `start` commnad
- update readme

### CODE REVIEW

**Comment by ujovlado** [comment]
Toto je vlastne "no brainer" no bol by som rad ak by to skusil niekto na Macu staci asi `yarn start` a ci to pofici. Napr. @kacurez ?

**Comment by kacurez** [comment]
ok mmnt

**Comment by ujovlado** [comment]
Parada, diky ... to bude ok, je tam urcite nejaky self signed cert webpacku.

**Comment by ujovlado** [comment]
Inac, mame to podobne aj na connection (https://localhost:8700), takze myslim cajk. :wink:

**Pull request merged**
