### PR TITLE
Fix completely broken MongoDB UI

### LINKED ISSUE #1392: broken ex mongo query detail page
vytvoril som si jednoduchu query a potom z indexu do nej vliezol:
https://connection.keboola.com/admin/projects/219/extractors/keboola.ex-mongodb/339893702/query/76104

image

image

pada to na tomto:
https://github.com/keboola/kbc-ui/blob/master/src/scripts/modules/ex-db-generic/react/pages/query-detail/QueryNav.jsx#L46

### PR DESCRIPTION
**Pull request by ujovlado**
Fixes #1392 

Proposed changes:

- Copied some components from ex-db-generic
- Customized ^ components
- Add missing functions
- Fix warnings and errors

Next time we (or I) should spent more time checking it :disappointed:

### CODE REVIEW

**Comment by pivnicek** [comment]
Sorry about this ujo :-(, I'll give it a pull and try it out.

**Comment by kacurez** [comment]
aha to az takto? som myslel ze ten fix bude jednoduchsi a aj som sa chcel do toho pustit ale som uz mal nieco rozrobene..tak to by som sa zamotal :)

**Comment by ujovlado** [comment]
Az take strasne to nebolo, no nesli pridavat nove query z query detailu (len z indexu). A ked uz sa ti ju podarilo pridat, tak si ju nevidel zase v sidebare v query detaile.

Toto je hotifx, zrefaktorujem to viac v ramci #1287

**Comment by pivnicek** [comment]
myslim ze git blame https://github.com/keboola/kbc-ui/commit/95b69d1f93d71dbfe9316b311a0074efd785d262#diff-60e707dd6dbcfb0a3bac233d091c5552

:-(

**Comment by pivnicek** [comment]
image
on the detail form

**Comment by pivnicek** [comment]
image
on press edit of existing query

**Comment by pivnicek** [comment]
ok @ujovlado, I found a couple warnings ^.

**Comment by ujovlado** [comment]
Those are minor, I know about them.

**Pull request merged**
