### PR TITLE
Allow deletion of linked bucket

### LINKED ISSUE #2930: Storage Explorer - linked bucket deletion disabled

### PR DESCRIPTION
**Pull request by ujovlado**
Fixes #2930

Proposed changes:

- Allow deletion of linked bucket

### CODE REVIEW

**Comment by ujovlado** [comment]
Popri review som si vsimol, ze neslo mazat linknute buckety, lebo maju permission "read".

**Comment by natocTo** [comment]
OK, nestačilo by jen `this.state.bucket.get('sourceBucket')` nebo `!!this.state.bucket.get('sourceBucket')`? Nebo to nemusí fungovat vždy? Ale to je drobnost.

**Comment by ujovlado** [comment]
Asi jo, je mi to fuk :)

**Comment by ujovlado** [comment]
Rebasnute

**Pull request merged**
