### PR TITLE
refactor ex-db-generic: refine and remove useless statements

### PR DESCRIPTION
**Pull request by kacurez**
Proposed changes:
- odstranuje zbytocny kod
- vzniklo z review a debaty v https://github.com/keboola/kbc-ui/pull/1535#pullrequestreview-108922687

### CODE REVIEW

**Comment by pivnicek** [comment]
imho maybe we can get rid of the static state stuff here too

**Comment by ujovlado** [comment]
@pivnicek it's already removed, isn't it? :)

**Comment by pivnicek** [comment]
@ujovlado I meant when you save credentials it triggers `props.isEnabled = false` and the form takes on the static version (and then it redirects).  Looks a little sloppy imho.

**Comment by ujovlado** [comment]
oh, I see, right. I thought you meant Edit/Save Credentials btns ;)

**Comment by kacurez** [comment]
good idea, I don't mind do it here or in other issue.

**Pull request merged**
