### PR TITLE
ex db credentials flow

### LINKED ISSUE #1663: Improve ex-db-generic credentials workflow
When you save credentials it briefly shows static form which looks kind of sloppy.

When saving, it's best just to disable the individual form elements.

### PR DESCRIPTION
**Pull request by pivnicek**
Fixes #1663 

Proposed changes:

- remove static forms
- remove elipses
- only test credentials on save if they had not been previously tested

### CODE REVIEW

**Comment by ujovlado** [comment]
@pivnicek what's the status of this PR? I found small bug in ex db credentials saving and thinking about credentials static state removal.

**Comment by pivnicek** [comment]
@ujovlado there is one remaining issue that I'm not 100% on how to solve.

When someone tests credentials and they are valid and then saves them, I want it to not check credentials again.  Right now it checks them again before fetching table listing.

Otherwise this PR is ready imho (If I remember correctly :-)

I'm going to finish https://github.com/keboola/kbc-ui/pull/1729 right now and then return to this.

**Comment by pivnicek** [comment]
@ujovlado btw, what is the small bug that you found?  I can check here if these changes fix it (and if not, add it here)

**Comment by ujovlado** [comment]
@pivnicek when saving credentials with SSL form, there's an render error while in static state (for a sec)

peek 2018-05-25 15-16

**Comment by pivnicek** [comment]
@ujovlado oh IC.  Ok, this PR will fix that.  Cheers!

**Comment by pivnicek** [comment]
I'll resolve the above conflicts now

**Comment by ujovlado** [comment]
Yep, that's why I asked what's the state ;)

**Comment by pivnicek** [comment]
wtf, this branch is a mess.  I'm going to make a clean one, sorry.

**Comment by ujovlado** [comment]
@pivnicek what's the motivation behind `NonStaticSshTunnelRow` component? It's because of `wr-db`?

**Comment by pivnicek** [comment]
@ujovlado yes, I thought it's easier to just make a new component than update the writers too.  When the writers get updated we can remove the old component.

**Comment by ujovlado** [comment]
ok, I thought so ... I'll check it again and merge

**Comment by ujovlado** [comment]
I don't like this commit "only test credentials on save if they haven't been tested" ... I think we should not disable "test credentials" button at all.

**Comment by ujovlado** [comment]
I'll revert it (or rebase). I remember there was issue when we enabled that button, so users will be able to test credentials anytime.

**Comment by ujovlado** [comment]
Oh, sorry, I thought it was about "test credentials" btn. :)

**Comment by pivnicek** [comment]
yeah, the change is that if testCredentials passes, it remembers that, and when you save, if the credentials are the same that have been tested it won't test again:)

**Pull request merged**
