### PR TITLE
WIP: External link

### PR DESCRIPTION
**Pull request by ujovlado**
Related to: #1529 

Proposed changes:

- component for external links

### CODE REVIEW

**Comment by ujovlado** [comment]
No a prave mi napadlo, ci to nehodim ako genericku komponentu do `indigo-ui`

**Comment by ondrejhlavacek** [comment]
https://github.com/keboola/kbc-ui/pull/1561/commits/751f775c6564780ff841207c4b0c7fa938afea70 by v tomhle PR vůbec být neměl ne?

**Comment by ujovlado** [comment]
Replaced by https://github.com/keboola/indigo-ui/issues/113 and https://github.com/keboola/kbc-ui/issues/1569

**Comment by ujovlado** [comment]
Nakoniec som z toho spravil functional component, odtialto to cherry-picknem

**Pull request closed without merging**
