### PR TITLE
table-preview: show last component update info

### LINKED ISSUE #1452: provide table origin info
Do table preview by sa hodilo info otom, ktorou komponentou a konfigom bola tabulka vytvorena + link na konfig.

Riesenie som uz implementoval v https://github.com/keboola/kbc-ui/pull/1129 ale to sa momentalne nehybe tak to aspon rozlozim. Imho sa to info dost hodi a nevidim dovod preco by to tam nemalo byt(napr ze to na nieco musi pockat..)

Moznou otazkou je ako to nazvat ale to sa da jednoducho upravit, navrhy:
- `Resulted From`
- `Origin` - to sa mi paci najviac.
- ...

takto by to vyzeralo.
image

### PR DESCRIPTION
**Pull request by kacurez**
Fixes #1452 

image

Proposed changes:

- Tyka sa to "table preview:General Info Tab" zobrazenej na stranke alebo cez modal
- zobrazi sa Last Component Update + link na konfig 
- vyuzivaju sa k tomu metadata tabulky (`KBC.lastUpdatedBy.component/configuration.id` + fallback na `KBC.createdBy.component/configuration.id`)
- ak zaznam alebo komponenta neexistuje tak sa zobrazi `N/A`

### CODE REVIEW

**Comment by ujovlado** [comment]
@ondrejhlavacek @pivnicek I need small advice here, what do you think about that "Last Component Update" label? I think there should be something like "Last update by" or "Recently updated by".

**Comment by pivnicek** [comment]
@ujovlado I like "Last updated by" for this.  I agree, I don't think it's necessary to say component here.

**Comment by ujovlado** [comment]
Another thing I don't like is the height of that icon - it's causing weird look of that row (is bigger that other rows) - I'll fix it.

**Comment by ujovlado** [comment]
Updated: 

screenshot_2018-02-27_13-29-41

**Pull request merged**
