### PR TITLE
Revert confirm buttons hotfix

### PR DESCRIPTION
**Pull request by ujovlado**
Related to #2404 
Related to #2347 

Proposed changes:

- Revert hotifx with `pull-right` (`text-right` is enough)

### CODE REVIEW

**Comment by ujovlado** [comment]
Merge after css is registered in KBC

**Comment by ujovlado** [comment]
omg, to bol zamrd :man_facepalming:

**Comment by janmichek** [comment]
o co slo? v cem byl zamrd?

**Comment by ujovlado** [comment]
Slo o toto: https://github.com/keboola/indigo-ui/pull/323#issuecomment-442150809

Neviem, ci som to  mergol moc skoro a malo tam byt este nieco dorobene, ale odstranenie

```css
.modal-dialog .modal-footer .btn-toolbar > .btn {	
  float: none;	
}
```
rozbilo pouzitie BtnToolbar, ktory nebol v ConfirmButtons.

Zamrd bol v tom, ze som si to vsimol az po release, a tak som musel rychlo aktivovat starsiu verziu, revrtnut to, a potom pripravit fix.

**Pull request merged**
