### PR TITLE
(ex-db-generic) disable run btn for editing queries

### PR DESCRIPTION
**Pull request by pivnicek**
Fixes: https://github.com/keboola/kbc-ui/issues/1262

### CODE REVIEW

**Comment by ujovlado** [comment]
@pivnicek shouldn't be disabled also "Enable/Disable" btn? (check mark).

**Comment by pivnicek** [comment]
I don't think it matters either way, but sure, it seems more consistent to disable it.

**Comment by ujovlado** [comment]
> I don't think it matters either way, but sure, it seems more consistent to disable it.

It matters. :)

Current state (while I'm in query detail):

- clicking enable/disable pristine query will enable/disable it
- clicking enable/disable in new query does nothing (which is weird)
- clicking enable/disable in saved (but dirty) query will enable/disable it

If we disable it:

- clicking enable/disable in new query won't be available (which is good - I wanted to fix it)
- clicking enable/disable in pritine query enable/disable it (same as before)
- but clicking enable/disable in saved (but dirty) query won't be available (which is weird, because it worked before)

So, I would vote for removing enable/disable button from query detail - and enable/disable will be available only in query list.

**Comment by pivnicek** [comment]
I disabled it and it seems ok to me.  I'm not sure what you mean by "saved, but dirty".

**Comment by ujovlado** [comment]
@pivnicek 

> "saved, but dirty".

it means I'm editing existing query - I saved it before but started editing again.

**Comment by pivnicek** [comment]
ah, I see.  this branch currently disables the button for all non-saved states in the detail page (new or editing, dirty or clean:).  

I can remove it from the page of course, but I tried it and it didn't look very good.

**Pull request merged**
