### PR TITLE
Update to React 14 (main issue)

### PR DESCRIPTION
**Pull request by ujovlado**
Tasks:

- [x] lib: `react` and `react-dom` to latest v14
- [x] lib: `react-datepicker` update
- [x] lib: `react-dnd` update
- [x] lib: `react-bootstrap` update
- [x] lib: `react-autosuggest` @kacurez 
- [x] usage: `react-autosuggest` @kacurez https://github.com/keboola/kbc-ui/issues/876
- [x] usage: `react-datepicker` in google analytics (old and v4) @kacurez
- [x] usage: `react-dnd` in orch. phase edit 
- [x] usage: `keyMirror` from `fbjs` 
- [x] lib and usage `react-sticky` (calling deprecated React.findDom...)
  - [x] vyhodene, kde netreba: #917 
- [x] usage: fix as much as possible errors/warnings/deprecations (will help with next upgrade) 
- [x] check dependencies and move them to proper sections
- [x] lib and usage `react-select`: #932 

Use dom related function from `react-dom`:
- [x] `findDOMNode`
- [x] `render`
- [x] get rid of `getDOMNode` and use `ReactDOM.findDOMNode(this)` if needed

Load addons from separate packages:
- [x] `react-addons-test-utils`: only library
- [x] `react-addons-clone-with-props`: library and usage
- [x] `react-addons-pure-render-mixin` library and usage

---

Related issues/PRs:
- [x] CurrenUser to `.jsx` - preparation for fix of tags in ``: #822 
- [x] ^Fix of img tag: #824 
- [x] `ModalTrigger` replacements #826:
  - [x] Part 1: #828 @ujovlado
  - [x] Part 2: #840 @ujovlado
  - [x] Part 3: #846 @ujovlado
  - [x] Part 4: #874 @ujovlado, @kacurez 
  - [x] Part 5: #850  @pivnicek 
- [x] Update react bootstrap a dopisanie proxy modulov: #887 

---

Potom este:
- checknut autosuggest: @kacurez
  - [x] v tableselectore pouzitom v csv-import
  - [x] a s3
  - [x] google bigquery extractor
  - [x] autosuggest ... ma asi maly `z-index` tak pri pridavani output table (db extractor) je pod editaciou query ... ked tak upresnim
- skontrolovat ci ficia `refs` (bol problem v `ConfigurationTemplateSelector`, tak pre istotu): @ujovlado
  - [x] replacnut `this.refs.xxx.focus()` za `autoFocus` tam kde sa da
  - [x] Vyhodeny stary modul `SizeGraph`: #909 
  - [x] Prerobene `this.refs.xxx.focus()` za `autoFocus`: #912
---

Note that:

- this branch is rebased from time to time against actual master
- commits with `(f)` suffix will be rebased too
- many changes can be cherry-picked to master (some warnings fixes, etc.), so commits can change over time

### CODE REVIEW

**Comment by Halama** [comment]
Jak planujes update react-bootstrap? Bylo tam hromada nekompatibilit....

**Comment by ujovlado** [comment]
@Halama nieco fixnem search+replace ... no myslim, ze sme sa bavili, ze sa by sa spravi "react-keboola-bootstrap", ktory by previedol staru implementaciu na novu -> cize niektore casti asi tak, aby sa to cele nerozmrdalo

**Comment by kacurez** [comment]
react-datepicker je pouzitelny ale imo renderuje sa nejak divne zmenseny a nedari sa mi upravit jeho style. 

image

**Comment by ujovlado** [comment]
@kacurez na ten picker potom skusim kuknut

**Pull request merged**
