### PR TITLE
Revert "Revert "mysql ex incremental""

### PR DESCRIPTION
**Pull request by ujovlado**
Reverts keboola/kbc-ui#1691

### CODE REVIEW

**Comment by pivnicek** [comment]
@ujovlado I slightly refactored it to (hopefully) make the separation between the versions more clear (and fixed it, it was very stupid, sorry)

**Comment by ujovlado** [comment]
Ok, @pivnicek I fixed additional err introduced with that fix. It was stupid typo, but I would suggest less "fast&furious" way when coding - we do have time. Better proper fix than 3 rounds of fix/check. ;)

**Comment by ujovlado** [comment]
This PR was from me, I cannot req. review from myself. So I'll used the force :hammer: :stuck_out_tongue:

**Comment by pivnicek** [comment]
very fair comment :-). Smaller, less conditional PRs will help with that.  thanks @ujovlado

**Pull request merged**
