### PR TITLE
Add suggested datatypes for transformation inputs + fixes

### PR DESCRIPTION
**Pull request by ujovlado**
Reverts keboola/kbc-ui#1885 and adds new commit(s) to fix problem with datatypes.

@pivnicek new commits should be added here. Please keep commit 98e5239 untouched.

### CODE REVIEW

**Comment by pivnicek** [comment]
@ujovlado 6d0889d is a fix for the new table with no changes issue

**Comment by pivnicek** [comment]
image

**Comment by pivnicek** [comment]
Discovered an issue where if the datatype has `nullable` false, it's still checking convert empty values to null which it shouldn't be

**Comment by ujovlado** [comment]
@pivnicek there is still that little tricky thing while hovering

> Checkbox without label has bigger height than checkbox with label

Maybe @janmichek can help with it?

**Comment by Halama** [comment]
Investigating. This breaks whole transformation bucket. I cannot run even single transformation.
image

**Comment by pivnicek** [comment]
@Halama Is that running the transformation as-is without changing anything?

**Comment by Halama** [comment]
But otherwise it works great! I've tried it with few table without metadata and few tables with metadata provided by mysql extractor.

**Comment by pivnicek** [comment]
Ah, will need to make a max length check for varchars,  thanks for testing it!

**Comment by pivnicek** [comment]
I checked that transformation and there are no datatypes set.  In that case it should use the old defaults and not the metadata imho.

**Comment by Halama** [comment]
I think it is throw error because the whole transformation bucket is validated even if you are running single transformation. It is because dependent transformations. So this is validation message from transformation.

**Comment by pivnicek** [comment]
Ok, it's definitely an issue, I'll fix it asap:)

**Comment by Halama** [comment]
where you'll fix it in the ui or components?

**Comment by Halama** [comment]
Yes it is dependent on target engine which is conversion into snowflake data type in his case. But it can be also Redshift transformation.

**Comment by pivnicek** [comment]
Exactly, and each writer target in the future will have their own also.

**Comment by Halama** [comment]
I've found one minor issue in ui. If I create a new input mapping it is ok.
But if I for example add a new column the datatype for that new column is prefilled in the IM modal but after save it is not set.

**Comment by pivnicek** [comment]
ok! I'll make a list

- [ ] baseType length validation
- [ ] new column datatype save

**Comment by pivnicek** [comment]
@Halama The issue on column change is resolved,  and the maxLength thing should be too, but I need to confirm it, do you know which table this was from https://github.com/keboola/kbc-ui/pull/1886#issuecomment-434700813?

**Comment by Halama** [comment]
@pivnicek I am going to check it.

**Comment by Halama** [comment]
@pivnicek it is this table in.c-keboola-ex-db-mysql-364044166.dockeraccount and I think it is still same.

**Comment by Halama** [comment]
sorry, it was my fault everything look ok.

**Comment by pivnicek** [comment]
Maybe @padak wants to give it a try?

**Comment by Halama** [comment]
@padak will give it a try on production? :)

**Comment by padak** [comment]
Yes! I am on it in a minute

**Comment by padak** [comment]
@Halama ať na to koukám jak na to koukám, nevím co testovat. Všechno mi přijde stejný jako dřív.

**Comment by Halama** [comment]
@padak není to nasazený ještě, ráno to nasadíme. Tech komponent co poskytují metadata je zatím dost málo ale to dotáhneme průběžně. Brzo by to měly začít poskytovat unloady z workspace (transformace) a to pokryje dost tabulek.

**Comment by padak** [comment]
Vidím tam tohle:
image

Jestli to mám proklikat, tak dejte vědět až budu moct :)

**Comment by Halama** [comment]
@pivnicek asi myslel že si to zkompiluješ u sebe :) dáme vědět až to bude ready

**Comment by pivnicek** [comment]
@Halama jo, ok :-)

**Comment by padak** [comment]
To klidně můžu, ale když jste napsali

@padak will give it a try on production? :)

tak jsem myslel, že to tam je :) Jaká je to branch? Zkompiluju to!

**Comment by pivnicek** [comment]
@padak nechame to az rano to bude on production, promin za komplikace:)

**Comment by padak** [comment]
Jsem tam, vypadá to super!

**Pull request merged**
