### PR TITLE
Add compression option for ssh tunnel form

### LINKED ISSUE #2506: Support for compression in ssh tunnels
Add optional support for ssh tunnel compression.

### PR DESCRIPTION
**Pull request by pivnicek**
Fixes #2506 

Proposed changes:

-  If told to use it, the ssh form should also show compression checkbox

### CODE REVIEW

**Comment by pivnicek** [comment]
WIP

**Comment by ujovlado** [comment]
Should't we allow this by default on backend? Why to bother user if there's compression or not ... if using compression means it'll be faster, we should use it without asking.

**Comment by pivnicek** [comment]
I've been told that in most cases using compression actually makes it slower.

**Comment by ErikZigo** [comment]
@ujovlado https://keboola.slack.com/archives/C31U6BGJC/p1544445841187900?thread_ts=1544423464.180300&cid=C31U6BGJC

**Comment by ujovlado** [comment]
ok, I commented there :)

**Comment by pivnicek** [comment]
Dependent on pgsql backend first getting this live

**Comment by ujovlado** [comment]
I don't like this change, will wait for @padak's test. ;)

**Comment by padak** [comment]
MySQL server je v Bangalore, klienta mám v New Yorku:
image

...říká se mi to těžce, ale:

### SCP compressed, 1.2GB SQL file
```
root@padak-mysql-ex:~# scp -C /tmp/databig_plain.sql root@139.59.35.239:/tmp
databig_plain.sql                                100% 1214MB   8.8MB/s   02:18    
```

### SCP non-compressed, 1.2GB SQL file
```
root@padak-mysql-ex:~# scp /tmp/databig_plain.sql root@139.59.35.239:/tmp
databig_plain.sql                                100% 1214MB   8.8MB/s   02:18    
```

a 

### non-compressed mysqldump
```
root@padak-mysql-ex:/tmp# time mysqldump -u admin -h 127.0.0.1 -p padak databig > /tmp/databig_plain.sql
Enter password: 

real	2m6.530s
user	0m20.616s
sys	0m3.020s
```

### compressed mysqldump
```
root@padak-mysql-ex:/tmp# time mysqldump -u admin -h 127.0.0.1 -p padak databig > /tmp/databig_compressed.sql
Enter password: 
real	2m9.809s
user	0m23.884s
sys	0m5.240s
```

### Přenos gziped file - uncompressed spojení:
```
root@padak-mysql-ex:~# scp /tmp/databig_plain.sql.gz root@139.59.35.239:/tmp
databig_plain.sql.gz                                                                 100%  381MB   8.5MB/s   00:45    
```
### Přenos gziped file - compressed spojení:
```
root@padak-mysql-ex:~# scp -C /tmp/databig_plain.sql.gz root@139.59.35.239:/tmp
databig_plain.sql.gz                                                                 100%  381MB   8.5MB/s   00:45    
root@padak-mysql-ex:~# 
```

Takže na rychlý lince `-C` nemá žádnej vliv. Nezpomaluje to ani to nezrychluje. Doufám, že na shitty spojení to bude mít velkej vliv (bo nic než "doufám" mi teď nezbejvá) :)

**Comment by MiroCillik** [comment]
Super @padak diky za test, znamena to teda, ze sa to moze defaultne zapnut. A snad to teda pomoze na tych slabych spojeniach..

**Comment by padak** [comment]
za mě ano

--
Petr Simecek
+420 777 942 927

Blog http://padak.keboola.com/
Twitter https://twitter.com/petrsimecek
LinkedIn: http://linkd.in/simecekpetr
Calendar: http://bit.ly/petrsimecek



út 11. 12. 2018 v 11:56 odesílatel Miroslav Čillík <notifications@github.com>
napsal:

**Comment by pivnicek** [comment]
> znamena to teda, ze sa to moze defaultne zapnut

> za mě ano

@padak tak nepotrebujeme tu checkbox? vypdada ze ten compressed mysql-dump byl pomalejsi, ale jen trochu

**Comment by ujovlado** [comment]
Toto teda zavrem, je to podporovane rovno v extractore.

**Pull request closed without merging**
