### PR TITLE
Project overview - deprecated storage

### LINKED ISSUE #1075: Overview of deprecated stuff
Display a warning with a list of deprecated components/backends/features on project overview page.

- For components, it could call https://connection.keboola.com/v2/storage/components, to get a list of components in the project and get the deprecated ones. List of deprecated components will be hardcoded in the UI.

- Similarly for backends and features.

- Each item will contain a link to migration instructions and possibly a date, when the deprecated component will be migrated automatically or disabled.

### PR DESCRIPTION
**Pull request by Halama**
Fixes #1075 .

Proposed changes:

- New panel on project overview with deprecated mysql bucket warning and request to migration

image

### CODE REVIEW

**Comment by Halama** [comment]
Project with some MySQL buckets created https://connection.keboola.com/admin/projects/506

**Comment by ujovlado** [comment]
Mne tam ten text trosku zachadza. 
screenshot_2017-11-24_15-48-07

Chcel som to zmenit v CSSkach ale je to tam same `!important`. Hotifxnem to asi inline stylmi  a toto sa potom prehodi medzi prvymi do indigo-ui.

**Comment by Halama** [comment]
ok

**Comment by ujovlado** [comment]
Pozeram, ze tato podmienka je nejaka divna:
https://github.com/keboola/kbc-ui/blob/5c87d3415172de8b849fa5dcd21dd32526cf1813/src/scripts/modules/home/react/Index.jsx#L80-L82

... nejdem to ale riesit v tomto PR.

**Pull request merged**
