### PR TITLE
Pick rewrites 2 js from older branch

### PR DESCRIPTION
**Pull request by ujovlado**
Related to: #1170 
Related to: #1775 

I picked remaining rewrites from older branch and polished them.

Proposed changes:

- rewrite 4 components to JS

### CODE REVIEW

**Comment by ujovlado** [comment]
Ak treba, pushnem sem aj testy so snapshotmi, mam to lokalne.

**Comment by ujovlado** [comment]
Super, dik za check.

**Comment by ujovlado** [comment]
Este sa mi nepaci ta ErrorPage komponenta, poslem tam malu upravu.

**Comment by ujovlado** [comment]
v tomto su teda 2 podmienky, ktore treba splnit:
```coffee
if @state.error?.getExceptionId()
  ...
```
Fixnem

**Comment by kacurez** [comment]
aha jasne good point! Zvlastne tu error stranku som skusal ale nespadlo mi tak som to neriesil :)

**Comment by ujovlado** [comment]
no ono to nespadlo ... akurat ked tam prisiel error bez exceptionId, tak to napisalo undefined :) ... nic kriticke no nech je to na poriadku :)

**Pull request merged**
