### PR TITLE
refactor storage documentation

### PR DESCRIPTION
**Pull request by kacurez**
internal issue reference https://github.com/keboola/internal/issues/148
V tejto uprave pridavam testy a refactoring modulov okolo storage documentation. Na prvy pohlad tam je vela uprava ale vacsina su to snapshoty a testovacie data. Postupoval som tak ze najprv som si povodny `Documentation.jsx` rozdelil(zkopiroval kod) do `DocumentationUtils.js` a `DocumentationTable.jsx`, potom k nim napisal testy a potom zrefactoroval. Tiez som tam zmenil naming(napr enhancedBuckets -> documentationTree). Snazil som sa to zrefactorovat tak aby boli casti kodu znovupouzitelne a snad lepsie citatelne :)

Zrefactorovane moduly: 
- hlavny react page module `Documentation.jsx` https://github.com/keboola/kbc-ui/blob/kacurez-refactor-storage-documentation/src/scripts/modules/storage-explorer/react/pages/Documentation/Documentation.jsx
- `DocumentationUtils.js` https://github.com/keboola/kbc-ui/blob/kacurez-refactor-storage-documentation/src/scripts/modules/storage-explorer/react/pages/Documentation/DocumentationUtils.js obsahuje napr "hlavnu" funkciu na vytvorenie pomocnej struktury `createDocumentationTree`  a funkciu na generovanie markdowvnu `buildDocumentationToMarkdown`. Obe sa testuju v https://github.com/keboola/kbc-ui/blob/kacurez-refactor-storage-documentation/src/scripts/modules/storage-explorer/react/pages/Documentation/DocumentationUtils.spec.js
- `DocumentationTable.jsx` - render documentation tabulky https://github.com/keboola/kbc-ui/blob/kacurez-refactor-storage-documentation/src/scripts/modules/storage-explorer/react/pages/Documentation/DocumentationTable.jsx k tomu snapshot testy v https://github.com/keboola/kbc-ui/blob/kacurez-refactor-storage-documentation/src/scripts/modules/storage-explorer/react/pages/Documentation/DocumentationTable.spec.jsx

Ked sa tento PR mergne tak sa moze pokracovat v pridavani featur do ui documentation storage(pripravim issue na dalsi feature update).

### CODE REVIEW

**Comment by kacurez** [comment]
- presunul som `DocumnetationUtils.js` aj s testami do pages/Documentation zlozky ako si navrhoval, mne osobne to je jedno ci bude tam alebo tu :)
- pridal som `.md` priponu
- prettier som pustil ale nic to neurobilo `yarn prettier --config .prettierrc.js src/scripts/modules/storage-explorer/react/pages/Documentation/**` - ja mam ten prettier nainstalovany a obcas si ho pustim, tu som ho tiez parukrat pustal tak je mozne ze to je uz dostatocne zprefitifikovane.

**Comment by natocTo** [comment]
Supr. Na ten prettier tam ještě chybí --write přepínač

`yarn prettier --config .prettierrc.js --write "src/scripts/modules/storage-explorer/react/pages/Documentation/**"`

**Comment by kacurez** [comment]
ahaa dik :) tak pustil to stym

**Comment by ujovlado** [comment]
Asi by som do "actions" presunul aj `snapshotDocumentation`, inac to vyzera fajn.

**Pull request merged**
