### PR TITLE
Add teradata extractor

### LINKED ISSUE #1985: Add ex-teradata to ex-db-generic

### PR DESCRIPTION
**Pull request by pivnicek**
Fixes #1985 

Proposed changes:

- Add teradata extractor to ex-db-generic

### CODE REVIEW

**Comment by pivnicek** [comment]
on running single job page: `ReactErrorHandler.js:34 Error. Check render() method of component 'Link'. Error details: Error: Cannot find a route named "keboola.ex-teradata-row"`

**Comment by Actimel** [comment]
#1986 Should be merged here

**Comment by Halama** [comment]
@pivnicek  šlo by tohle mergnout už teď před bugfixem ##1989 ?

**Comment by ujovlado** [comment]
@pivnicek should I review this or it is waiting for mentioned PR in mysql ex?

**Comment by Actimel** [comment]
@ujovlado I rebased it, pls review.

**Comment by pivnicek** [comment]
@ujovlado, I'll release a new mysql version, mmt

**Comment by pivnicek** [comment]
https://github.com/keboola/db-extractor-mysql/releases/tag/3.2.0

**Comment by ujovlado** [comment]
ok, I'll postpone this until https://github.com/keboola/db-extractor-mysql/issues/59 is fixed

**Pull request merged**
