### PR TITLE
Show creation date in configuration lists

### LINKED ISSUE #1012: add date created to config listing
Currently says `created by whoever@wherever.com` but imho it would be awful nice to have the date there too:)

### PR DESCRIPTION
**Pull request by ujovlado**
Fixes #1012

### CODE REVIEW

**Comment by ujovlado** [comment]
V komponentach:

screenshot_2017-10-03_23-13-49

V Detaile:
screenshot_2017-10-03_23-14-36

**Comment by ujovlado** [comment]
Tu este rozmyslam, co ma vacsiu vahu, a teda ci to bude "Created 2 months ago by vlado" alebo "Created by vlado 2 months ago". Viac sa mi pozdava 1., zmenil by som to.

**Comment by pivnicek** [comment]
I think "Created by vlado 2 months ago" is fine tbh.

**Comment by ujovlado** [comment]
@pivnicek ok, I leave it that way. Those information have probably same "weight", Thanks!

**Comment by janmichek** [comment]
Me to teda moc nebavi :] ale pohybujem se na urvni nazoru
- vadi mi to ruzny
- jedna ikonka je symbol, jedna ikonka je ovaldaci prvek

Zatim budiz, nechme to tak. ZKusim se nad tim zamyslet

**Pull request merged**
