### PR TITLE
Geneea nlp fixes

### PR DESCRIPTION
**Pull request by kacurez**
modules/geneea-nlp-analysis-v2

- fix - disable save button if mandatory params missing or empty: https://keboola.slack.com/archives/C03SE0YS3/p1509120256000045
- refactor - get rid of console warnings

### CODE REVIEW

**Comment by ujovlado** [comment]
@kacurez pls toto mozem mergnut?

**Comment by kacurez** [comment]
@ujovlado jj zamna to je k nasadeniu

**Comment by kacurez** [comment]
tak este tam pridam malicky fix, mmnt

**Comment by kacurez** [comment]
este cakam na dodanie popisu do helpu
vid https://keboola.slack.com/archives/C03SE0YS3/p1509443230000215

**Comment by ujovlado** [comment]
ok, requestni potom review ked tak ;)

**Comment by ujovlado** [comment]
@kacurez neozvali sa? nech nam to tu nevyschne

**Comment by kacurez** [comment]
@ujovlado napisal ze to doda. Imho v tomto PR neni ziadny blocker hotfix takze mozme pockat.

**Comment by kacurez** [comment]
@ujovlado tak to mozme mergnut, popis je dodany a doplneny, diky ;)

**Comment by pivnicek** [comment]
@kacurez shouldn't the output table description go into the table description?  I mean, the module can write this, no?

**Comment by kacurez** [comment]
@pivnicek good point! but the geneea app is creating the table so it would have to update it in manifest I guess, is it possible?

**Comment by pivnicek** [comment]
Yup, totally possible.  See https://github.com/keboola/darksky-augmentation/blob/master/src/Keboola/DarkSkyAugmentation/UserStorage.php for a simple example.

**Comment by ujovlado** [comment]
Tych warningov je tam este zopar, no poriesil by som to v nejake dalsej iteracii spolu s upravami toho formulara (a pripadnym prerobenim na verziu bez stratickeho stavu).

**Comment by kacurez** [comment]
zamna to cele je zrele na prepis(k lepsiemu a konzistentnemu ux) ale do toho som sa teraz nechcel pustat.

**Pull request merged**
