### PR TITLE
fix (GooglePicker): removed redundant scope

### PR DESCRIPTION
**Pull request by MiroCillik**
Removed redundant `spreadsheets.readonly` scope. 

It is not needed for google drive picker duties.

### CODE REVIEW

**Comment by ujovlado** [comment]
@MiroCillik toto tam chces poslat hned? Robim nejaku cistku PR, tak to mozem odpalit :)

**Comment by MiroCillik** [comment]
@ujovlado mozes to mergnut, diky ;)

**Comment by MiroCillik** [comment]
Nakoniec sme si uvedomili, ze ten scope potrebuje Google Drive Extractor, kde vyberas sheet, ktory chces sitahnut... 🤦‍♂

**Comment by ujovlado** [comment]
Super :)

**Pull request closed without merging**
