### PR TITLE
Replace NotAvailable Component

### PR DESCRIPTION
**Pull request by janmichek**
Fixes https://github.com/keboola/indigo-ui/issues/249

### CODE REVIEW

**Comment by janmichek** [comment]
Pro snazsi kontrolu pridavam link na vyskyt v lokalni verzi KBC (bez tokenu samozrejme). Nekde jsem nevedel jak nasimulovat hodnotu, tak jsem negoval podminku zobrazeni komponenty

UsageByMonth.jsx + CreditSize.jsx
http: //localhost:3000/?token=4904-#/settings-project-power

FileInputMappingDetail.jsx
http: //localhost:3000/?token=4904-#/applications/dca-custom-science-python/467247096

JobRow.jsx
http: //localhost:3000/?token=232-#/jobs

ValidUntil.jsx
http: //localhost:3000/?token=4904-#/transformations/sandbox

EventDetail.jsx
http: //localhost:3000/?token=4904-#/jobs/470549006?q=&eventId=1162479750

FiltersDescription.jsx
http: //localhost:3000/?token=4904-#/applications/geneea.nlp-analysis-v2/460670007

SelectBucket.jsx
http: //localhost:3000/?token=258-#/writers/wr-portal-sas/432111408

MigrationRow.jsx
http: //localhost:3000/?token=232-#/extractors/ex-google-analytics

HeaderColumnsMultiSelect.jsx (kod je stejne zakomentovany)
http: //localhost:3000/?token=4904-#/extractors/keboola.ex-google-drive/431223374

FilesList.jsx
http: //localhost:3000/?token=4904-#/writers/keboola.wr-google-drive/407458026

GaMultiSelect.jsx
http: //localhost:3000/?token=4904-#/extractors/keboola.ex-google-analytics-v4/408517101/query/40216

geneea-nlp-analysis-v2\react\Index.jsx
http: //localhost:3000/?token=4904-#/applications/geneea.nlp-analysis-v2/460670007

QueriesTable.jsx
http: //localhost:3000/?token=4904-#/extractors/keboola.ex-facebook/407457345

UrlParserModal.jsx
http: //localhost:3000/?token=4904-#/extractors/keboola.ex-google-analytics-v4/408517101/new-query

GeneralInfoTab.jsx + TableUpdatedByComponentInfo.jsx + formatCardinalNumber.js
http: //localhost:3000/?token=4904-#/extractors/radektomasek.ex-dropbox-v2/470304888/tables/in.c-radektomasek-ex-dropbox-v2-470304888.AssetsImportExtendedSample

ProfilesManagerModal.jsx
http: //localhost:3000/?token=4904-#/extractors/keboola.ex-google-analytics-v4/467235212
QueryEditor.jsx

http: //localhost:3000/?token=4904-#/extractors/keboola.ex-google-analytics-v4/408517101/new-query
EventDetailModal.jsx + BucketTables.jsx

JobDetail.jsx
http: //localhost:3000/?token=4904-#/jobs/470516078?q=

Table.jsx
http: //localhost:3000/?token=4904-#/writers/keboola.wr-db-mysql/435052028/table/in.c-csv-import.407799760

orchestration-job-detail\Overview.jsx
http://localhost:3000/?token=4904-#/orchestrations/439134361/jobs/470757199

GoodDataStats.jsx
http: //localhost:3000/?token=4904-#/jobs/465594490?q=gooddata

TasksEditTableRow.jsx
http: //localhost:3000/?token=4904-#/orchestrations/439134361/tasks

TableOutputMappingDetail.jsx
http: //localhost:3000/?token=4904-#/applications/dca-custom-science-python/467247096

InputMappingDetail.jsx
http: //localhost:3000/?token=4904-#/transformations/bucket/470302553/transformation/470302580

OutputMappingDetail.jsx
http: //localhost:3000/?token=4904-#/transformations/bucket/464917938/transformation/464917945

TasksTableRow.jsx
http: //localhost:3000/?token=4904-#/orchestrations/439134361/tasks

modules\apify\react\Index\Index.jsx
http://localhost:3000/?token=4904-#/extractors/apify.apify/463538671

StorageApiTableLinkEx.jsx
http://localhost:3000/?token=4904-#/extractors/keboola.ex-facebook/407457345

EventDetailModal.jsx + BucketTables.jsx
storage explorer - vyviji se

settings-users.js
Bohuzel nejde v lokalnim kbc overit

GeneralInfoTab.jsx
Bohuzel nejde v lokalnim kbc overit


FileOutputMappingDetail.jsx + FileOutputMappingHeader.jsx
Tohle si pamatuju ze je v nejaky deprecated applikaci, ale uz jsem to nedohledal. Pouziva se to jeste vubec?

**Comment by janmichek** [comment]
Koukam ze failuje ten test, protoze jsem si indigo pripojil lokalne. Takze na ten test udelam extra issue

**Comment by janmichek** [comment]
Vsude po aplikaci uz empty stav vypada jednotne. S odlisnym stylem to teda nevypada ze neco ma hodnotu 'N/A'. Posledni misto kde trochu vaham je umisteni v labelu.

image

Byl bych rad, aby to vypadalo jednotne napric celou aplikaci, takze bych vubec label (filesize) 'N/A' nezobrazoval, pokud je prazdny. S hodnotou samozrejme ano.
Alternativne se to da vyresit stylem s bilym pismem, ale prefejuju spis to prvni.

**Comment by janmichek** [comment]
V mappingu se tedy zobrazi jen label s filesize.

**Comment by ujovlado** [comment]
Toto som vyriesil v indigo-ui jednou css triedou, nema vyznam to implementovat tu, ked robime novy design.

**Pull request closed without merging**
