### PR TITLE
Replace ModalTrigger with Modal (step 5)

### PR DESCRIPTION
**Pull request by pivnicek**
- [X] ex-google-drive-old
- [x] ex-google-analytics-old
- [x] gooddata-writer (1)
- [x] gooddata-writer (2)

### CODE REVIEW

**Comment by pivnicek** [comment]
Warning: Still labeled [WIP] because I want to confirm functionality of the LoadType modal before merging.  that one was a bit hairy :)

**Comment by ujovlado** [comment]
@pivnicek I'll check it and later you'll check transformations for me

**Comment by ujovlado** [comment]
I removed that `RunExtraction`, since it wasn't used at all: https://github.com/keboola/kbc-ui/search?utf8=%E2%9C%93&q=RunExtraction

**Comment by pivnicek** [comment]
omg, how did I think the config row was using that?  good grief.  diky

**Comment by ujovlado** [comment]
I checked it and everything works fine.

But regarding ad45b28 imho will be better to:
- revert it and keep only "modal trigger" changes
- and then move modal to separate file `LoadTypeModal.coffee`

**Comment by pivnicek** [comment]
Ok, we have a difference of opinion:)

Mainly because there is no reason for 2 classes here (as ad45b28 demonstrates),  this is (and should be) the modal class file.
I would actually push for further refactoring (putting `incrementalLoad` into state for example) but I refrained from doing it in the spirit of "just changing this from ModalTrigger" which I think has been done.

**Comment by ujovlado** [comment]
I see your point here and agree. It's more clearer in the morning :wink: ... so I'll check it last time and merge. Thanks!

**Pull request merged**
