### PR TITLE
Project power and limits

### PR DESCRIPTION
**Pull request by ujovlado**
- Current month set as expanded in "last month usage" (right side)
- Ability to hide limit from limits page (filter by `showOnLimitsPage`)
- Add new section with Project Power Limit (left bottom side)

screenshot_2017-01-18_20-12-25

### CODE REVIEW

**Comment by pivnicek** [comment]
looks good, but it seems strange to me to have "credits" following each value in the table.  Could it be a column label maybe?  Might have to move total to the bottom in that case.  I'm not sure.

**Comment by ujovlado** [comment]
@pivnicek that "credit" thing is already there ... this is about "consumption" at bottom left ;) But I'll try to remove "credit suffix" from that table and we'll see

**Comment by Halama** [comment]
Ono to ten limit a tu aktuální hodnotu nečtě z tech limitů ale spočítá to přímo z tech dat co poskytne queue že? Asi by bylo lepší kdyby to tu hodnotu bralo přímo z limitů a plnilo ji to podobně jako tady https://github.com/keboola/connection/blob/master/application/modules/storage/cli-commands/SnapshotProjectMetrics.php#L84

**Comment by ujovlado** [comment]
@Halama no tomu som sa prave chcel vyhnut, tlacit to cez keen. Ci je nutne tie data mat dostupne historicky?

**Comment by Halama** [comment]
ne keen, to co jsem nalinkoval prave jenom nastavi tu aktualni hodnotu, prepisuje ji kazdy den. tak by to melo byt at se to necte odjinud.

**Comment by Halama** [comment]
takze v tom commandu co jsem nalinkovat proste zjistis project power od zacatku mesicu a nastavis ho jako metriku projektu https://github.com/keboola/connection/blob/master/application/modules/storage/cli-commands/SnapshotProjectMetrics.php#L141

Akorat teda aby to iterovalo pres vsechny projekty asi neni uplne dobry.

**Comment by Halama** [comment]
mozna na to zatim teda kasli

**Comment by ujovlado** [comment]
kedze sa tu bude dat upravovat limit na inej stranke, bude este nutna uprava na connectioin (admin module, je tam redirect po uprave limitu) ... oznacujem radsej ako WIP

**Pull request merged**
