### PR TITLE
Documentation badge

### LINKED ISSUE #1782: documentation link
show documentation link also somewhere on the configuration list page

/extractors/keboola.ex-facebook/405165555
has
image

/extractors/keboola.ex-facebook has nothing

### PR DESCRIPTION
**Pull request by ujovlado**
Fixes #1782 

Proposed changes:

- Show link to documentation on component detail page (if available)
- Add new functions to filter (include, exclude) badges
- Remove filtering from ComponentBadgeCell - all components now only "consuming" badges

screenshot_2018-08-08_15-15-30

### CODE REVIEW

**Comment by janmichek** [comment]
Vidim tady jenom schyzu v tom symbolu - otaznik vs kniha

image

Bude to teda jen na detailu komponenty jo? Pokud by to melo byt v gridu vyberu novy komponenty, tak s tim napisem mi prijde ze to zabira dost mista.

**Comment by ujovlado** [comment]
Aha, jasne, zmenim to na `fa-question-circle`, to sa pouziva castejsie. :+1: 

Ano, podla toho, co sme debatovali v #1782 a na Slacku, tak by to malo byt zatial len v detaile komponenty.

**Comment by odinuv** [comment]
asi bych tam chtel nejak mit, ze je to *dalsi* dokumentace (veci, ktere ji nemaji, nejsou nutne undocumented, mozna to proste potrebuji) - additional/supplemental documentation is available @hhanova ?

**Comment by ujovlado** [comment]
Len doplnim, ze takto to presne chcela Hanka: https://keboola.slack.com/archives/C0A5ZK1LY/p1530175840000236

**Comment by ujovlado** [comment]
@odinuv ak by to ale solvlo pridanie slovicka "Additional", dam to tam aj hned a upravit to mozeme aj neskor ;)

**Comment by ujovlado** [comment]
ok, dam tam "Additional" a nasadim to

**Pull request merged**
