### PR TITLE
Prefer user defined types

### PR DESCRIPTION
**Pull request by pivnicek**
Followup on #3102

Proposed changes:

- using user defined types in IM if present

### CODE REVIEW

**Comment by pivnicek** [comment]
Only the last 2 commits are relevant here, the others are from #3102

**Comment by ujovlado** [comment]
Rebasol som to, pride mi, ze to fici dobre. Este by som pockal na potvrdenie @natocTo.

**Comment by ujovlado** [comment]
Vsimol som si tam jednu chybu, ale to nesuvisi s tymto issue.

**Comment by ujovlado** [comment]
Ozaj, a nemali by sme nastavit "empty values as null", ak je dany column `nullable`?

**Comment by ujovlado** [comment]
@pivnicek shouldn't we set "empty values as null" if column is nullable?

**Comment by ujovlado** [comment]
ok, it's a bug.

**Comment by ujovlado** [comment]
I'll fix it and then we can release it.

**Comment by ujovlado** [comment]
Necham to na dalsi PR nakoniec. Je to o tom, ze by to malo akceptovat viac "truthy" a "falsy" values.

**Comment by natocTo** [comment]
Jo něco takového

> Necham to na dalsi PR nakoniec. Je to o tom, ze by to malo akceptovat viac "truthy" a "falsy" values.

Něco v tom smyslu jsem dodělával do toho předešlého PR.

https://github.com/keboola/kbc-ui/blob/97520d5c72fe6b5161e53876a2bff27f54d0fb61/src/scripts/modules/components/utils/datatypeHelpers.js#L36

**Comment by ujovlado** [comment]
a kua, to som si nevsimol.

**Comment by ujovlado** [comment]
opravene podla toho, co si pisal (#3211)

**Pull request merged**
