### PR TITLE
[ex-db-row-config] Only set query or table, not both

### LINKED ISSUE #2060: [ex-db-mysql]  Advanced query in config row contains null for table
This causes a configuration exception, as both query and table cannot be set

### PR DESCRIPTION
**Pull request by pivnicek**
Fixes #2060 

Proposed changes:

-

### CODE REVIEW

**Comment by pivnicek** [comment]
@ujovlado not sure if you've seen this, but it's  very small change that will fix #2060 .

**Comment by ujovlado** [comment]
I've seen, it'll merged in 10 minutes.

**Comment by ujovlado** [comment]
I understood this change, but I wasn't able to reproduce it - to set that `table` to `null`.

**Comment by pivnicek** [comment]
> I understood this change, but I wasn't able to reproduce it - to set that table to null.

You'd need to migrate an advanced query to row configuration.

**Comment by ujovlado** [comment]
Ok, whatever. I migrated, no success :-D (not worth to burn the time)

**Pull request merged**
