### PR TITLE
(ex-db-generic) PK validation

### PR DESCRIPTION
**Pull request by pivnicek**
Fixes: #1285 
Fixes: #1261

### CODE REVIEW

**Comment by pivnicek** [comment]
@ujovlado This "does the job" but I'm not happy with the button (pencil).  I like how it "fixes it" for you, but I think it could be done maybe in a better way.  Anyhow, suggestions very welcome:)

**Comment by ujovlado** [comment]
I think, the classic text will be enough.

screenshot_2017-11-21_19-30-49

**Comment by ujovlado** [comment]
peek 2017-11-21 20-09

**Comment by pivnicek** [comment]
Thanks @ujovlado looks great!

**Pull request merged**
