### PR TITLE
(ex-db-mysql) make credentials database optional

### LINKED ISSUE #1264: New DB ex - UI glitch
Pro zadání credentials vyžaduje extraktor zadat jméno databáze (já ji například neznám přesně z paměti). 
image

Když ji zadám, můžu uložit credentials a pak mě to nabídne vylistovat tabulky ze všech dostupných databází:
image

Tohle je "pat" a to pole "Database" bych udělal nepovinné.

### PR DESCRIPTION
**Pull request by pivnicek**
ref: https://github.com/keboola/kbc-ui/issues/1264

edit, vlado:

Fixes #1264

### CODE REVIEW

**Comment by ujovlado** [comment]
Nice fix! I will add a small "excalamation" icon there - because at first I didn't notice that there is some text about not specified database.

screenshot_2017-11-15_15-49-45

**Comment by ondrejhlavacek** [comment]
careful here, this sounds like form validation and it should follow some rules (eg. all field descriptions should be under the input field). cc @janmichek

**Comment by ujovlado** [comment]
I mean, it's not a description for that field.

**Comment by ujovlado** [comment]
I'm going to merge this, because it's fixing actual problem. Later, in another issue we can discuss that "note" position.

**Pull request merged**
