### PR TITLE
Add datatypes to ex-db-generic column selector

### LINKED ISSUE #2040: [ex-db-generic] show data types of columns
When selecting columns it would be helpful to see what datatype they are.  
That information is available already, it's a question of how to display it.  
In the select box as part of the item label would be my guess.

### PR DESCRIPTION
**Pull request by pivnicek**
Fixes #2040 

Proposed changes:

- Add datatypes to ex-db-generic column selector

### CODE REVIEW

**Comment by ujovlado** [comment]
@pivnicek why is this change so complicated?

Isn't enough something like:

```diff
diff --git a/src/scripts/modules/ex-db-generic/react/components/QueryEditor.jsx b/src/scripts/modules/ex-db-generic/react/components/QueryEditor.jsx
index 722112596..34ed2e3c7 100644
--- a/src/scripts/modules/ex-db-generic/react/components/QueryEditor.jsx
+++ b/src/scripts/modules/ex-db-generic/react/components/QueryEditor.jsx
@@ -247,7 +247,7 @@ export default React.createClass({
 
     return _.map(columns, function(column) {
       return {
-        label: column.name,
+        label: column.type ? (column.name + ' [' + column.type.toUpperCase() + ']') : column.name,
         value: column.name
       };
     });
```

**Comment by janmichek** [comment]
I wasn't really able to find the purposed changes. If its's whitin particular configuration, please send me link and invitation to your project. Or if its a small visual change, screenshot of few occurences would be beneficial. Thx

**Comment by pivnicek** [comment]
haha @ujovlado yes, thank you

**Comment by pivnicek** [comment]
@janmichek you can see it in any database extractor.  All db extractors are configured in project 2703 (https://connection.keboola.com/admin/projects/2703)

**Comment by ujovlado** [comment]
@janmichek kedze je to v sulade s tym, co si navrhol, dam tomu este review a mergnem to

**Comment by janmichek** [comment]
Za me ok, nerikam ze je to nejaka vizualni bomba. Tady nemusi byt, ale svuj ucel to splnuje

**Pull request merged**
