### PR TITLE
Tune db ex config index

### PR DESCRIPTION
**Pull request by ujovlado**
Related #3105 

Proposed changes:

- New `Source` column (shows `SQL` label for custom query)
- Incremental and Primary Key grouped to Load Options
- Output Table renamed to Destination

Screenshot 2019-03-28 at 17 55 46

### CODE REVIEW

**Comment by ujovlado** [comment]
Ladil som to trosku dlhsie aby to nebolo tak natlacne (preto zoskupenie do Load Options) a zobrazilo sa fajn aj na mensej obrazovke (napr. 1440px na sirku). Myslim, ze to vyriesi ten problem co tam mame.

Screenshot 2019-03-28 at 16 04 04

**Comment by pivnicek** [comment]
I tried it on some of my test configs.  I'm not sure about aesthetics...
image

**Comment by pivnicek** [comment]
How about combining source and destination under title Mapping?

Like maybe
Name | Mapping | Load Options
========================
some name | source: schema.table | primary key: id, typ
                       destination: link           | incremental
-------------------------------------------------
?

**Comment by ujovlado** [comment]
@pivnicek feel free to try it and paste screenshot here :)

**Comment by ujovlado** [comment]
Co este moze vyzerat divne, ze je tam zrazu nieco malym, to vyhodim prec.

**Comment by ujovlado** [comment]
@pivnicek I tried many options (even combining src/dest) but it looked weird.

**Comment by pivnicek** [comment]
@ujovlado yeah, I played with it before too (hadn't tried the option you have here though!).  It's a hard one (for me at least).  imho this version (yours) is better than the current version and any that I tried.

**Comment by ujovlado** [comment]
Basically, it is very hard to combine src/dest and display it in one table cell and make it look good and without additional labels like we have in Files: 

Screenshot 2019-03-28 at 16 39 47

In db-ex there are much longer table names and wrapping is applied.

**Comment by pivnicek** [comment]
yeah, I agree, fwiw, this was my attempt 
image

**Comment by ujovlado** [comment]
@padak ked kuknes do uvodneho komentara v tomto issue, pokryva to, co chces? ak ano, podobnu vec pridame potom aj do query detail, do sidebaru (to spominam tu: https://github.com/keboola/kbc-ui/issues/3105#issuecomment-477642088) ... jedna sa mi hlavne o Source Schema and Table.

**Comment by padak** [comment]
@ujovlado je to super! ❤️

**Comment by pivnicek** [comment]
@ujovlado 
How about a little column heading change like this?
image

**Comment by ujovlado** [comment]
@pivnicek good idea 👍

**Comment by ujovlado** [comment]
@natocTo diky, dobry postreh.

**Pull request merged**
