### PR TITLE
Fix getPKColumns Type Error

### LINKED ISSUE #2409: TypeError: this.props.getPKColumns(...).map(...).toList is not a function
https://sentry.io/keboola/keboola-connection-ui/issues/780516254/?referrer=github_plugin

```
TypeError: this.props.getPKColumns(...).map(...).toList is not a function
  at HTMLDocument.nrWrapper (/admin/projects/500/extractors:5:12199)
...
(13 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by pivnicek**
Fixes #2409 

Proposed changes:

- return empty maps instead of js arrays for no pks found.

### CODE REVIEW

**Comment by pivnicek** [comment]
omg, what is 6a1a05b doing there

**Comment by ujovlado** [comment]
> omg, what is 6a1a05b doing there

because you didn't created on top of latest master

**Comment by pivnicek** [comment]
Sorry, I'll get rid of it.

**Comment by ujovlado** [comment]
i't already gone ;)

**Comment by pivnicek** [comment]
🤦‍♂️ ofc.  thanks ujo

**Pull request merged**
