### PR TITLE
(ex-db-generic) test connection validity

### LINKED ISSUE #1337: (ex-db-generic) - confirm valid connection before attempting table list fetch
The issue:

Currently it will attempt to fetch the table list if it sees that the credentials are valid, but it does not check that the connection is valid.  This will cause the getTables to timeout.  Get tables shouldn't be used as a connection verification tool in this way.

The solution:

On configuration load it should call testConnection if valid credentials are present and set a state attribute `connectionValid`.  The `connectionValid` attribute can be displayed on the right sidebar, and the `getTables` will only be called if it is `true`.  Lastly, any `onChange` in the credentials will set this to `false`, and it will be set to true again if `testConnection` succeeds.

### PR DESCRIPTION
**Pull request by pivnicek**
Fixes #1337   .

Proposed changes:

- Test Saved Credentials before fetching table listing.
- Separate error handling for connection errors and getTables errors
- Common table loading class for main form and quickstart

### CODE REVIEW

**Comment by pivnicek** [comment]
todo: 
- [ ] unsupported getTables components
- [ ] mongo

**Comment by pivnicek** [comment]
Follow up todo:
- [ ] Refresh link - only show if connection valid
- [ ] Add refresh link to detail form

**Comment by ujovlado** [comment]
@pivnicek 

### Icons

for database credentials status I would prefer something like this:

`fa fa-check-circle`:

screenshot_2017-12-07_12-21-45

and `fa fa-times-circle`:

screenshot_2017-12-07_12-23-29

... or get rid of `fa-user` icon and put status icon there (as you did with job status icon)

### Wrong credentials

screenshot_2017-12-07_12-25-37


Also few notes about "failed" credentials:

- IMHO there should be only one link to "credentials page" if I have wrong credentials
- message about tables is pointless (If I have wrong credentials, I cannot select tables)

### First setup

Fresh configuration shows this after few seconds (I didn't touch anything):

screenshot_2017-12-07_12-32-34

### Stuck loader

- Right after configuration go to Credentials page and than back to index

peek 2017-12-07 12-42


### Other

- If I tested connection in credentials page, is another testConnection call needed when I return to index page?

**Comment by ujovlado** [comment]
@pivnicek I rebased it, pls checkout fresh branch from remote.

**Comment by pivnicek** [comment]
Thank you @ujovlado !  I will update accordingly:)

Regarding
> Other
> If I tested connection in credentials page, is another testConnection call needed when I return to index page?

Yes it will because the testCredentials button does not save the credentials.

**Comment by pivnicek** [comment]
@ujovlado I've updated it with your feedback in mind.

2 things, 
1) what is the red you are using for `fa fa-times-circle` and 
2) I can't decide which link to the credentials page to remove:)

**Comment by ujovlado** [comment]
@pivnicek I checked it ... it looks good.

- that color was color from `label-danger` (I will update it ;) )
- regarding that "double link" I will prefer to keep the first (see proposal bellow)

So we can go from this:

screenshot_2017-12-12_14-14-00


To this (which is very similar to screen when you do not have credentials):

screenshot_2017-12-12_14-21-13


BTW, I like that "Asserting connection validity ..." screen :+1:

**Comment by ujovlado** [comment]
@pivnicek I did rebase :)

**Comment by ujovlado** [comment]
@pivnicek I'm going to update also second part

**Comment by ujovlado** [comment]
Ok, I think we "overthink" it a bit, so here's the result:

- I removed those "status" icons ... IMHO it will not give additional value to user, but it can cause confusion (that red `fa-times` icon looked like we create button for db credentials deletion) ...
- I split TableLoader to 2 components, because in query editor is needed different markup, than in quick start.

**Comment by ujovlado** [comment]
### No tables

screenshot_2017-12-12_17-52-33

### With tables

screenshot_2017-12-12_17-52-06

### In detail

screenshot_2017-12-12_17-52-17

**Comment by ujovlado** [comment]
From my point of view, it's ready. I'll wait few hours (or until tomorrow) and merge it.

**Comment by pivnicek** [comment]
Thanks @ujovlado.

I actually really liked the indicator on the sidebar that showed whether connection is valid or not, but maybe that's something we can ask at #uiux.  To me it re-assures me as a user that there is no connection issue.

But, since other components don't have that, maybe we can postpone it until all (or more) components want to show connection validity.

**Comment by pivnicek** [comment]
Otherwise I'm fine with it.  To be honest, my main intention for this was to separate the concerns of testing credentials and fetching table listing.   So please merge whenever you like.  Thanks ujo.

**Comment by ujovlado** [comment]
@pivnicek I liked it too. But more I clicked through the UI more I wasn't sure if it's good idea. Specially in right sidebar, when we're using those icons within menu items (fa-user = credentials, fa-play = run extraction, fa-trash = delete something, etc.). And with that fa-check/fa-times it looked like it indicates something else, which doesn't fit there. :)

**Comment by pivnicek** [comment]
@ujovlado yeah, I get that,  I say we throw it to the J's in #uiux.  Thanks again for the updates.

**Pull request merged**
