### PR TITLE
Simple table & columns select for db-extractors

### PR DESCRIPTION
**Pull request by pivnicek**
Ready for final review.

outstanding issues:
- [x] unsupported extractors not working properly
- [x] broken mysql ssl tab

outstanding minor things:

- [x] poorly aligned new query button on index page

### CODE REVIEW

**Comment by ondrejhlavacek** [comment]
I'm getting this error when loading

image

**Comment by ondrejhlavacek** [comment]
If there's no connection, I'm left with this

image

image

**Comment by ondrejhlavacek** [comment]
Created a new extractor config

image

image

**Comment by ondrejhlavacek** [comment]
Add Query button has a weird font.
image

**Comment by ondrejhlavacek** [comment]
Spinners do not sit on the baseline

image

**Comment by ondrejhlavacek** [comment]
image

mixed case for placeholders

**Comment by ondrejhlavacek** [comment]
How about the Autosuggest opens immediately after you click in the input? I have no idea the autosuggest is there until I start typing

pjolbrwyrn

Question wrt the autosuggest - what if it's only a dropdown/selectbox? Does it make sense to allow non-existing tables?

**Comment by ondrejhlavacek** [comment]
image

The query should encapsulate the column / table identifier

**Comment by ondrejhlavacek** [comment]
What if the query editor is a 2 state with a flip switch between manual mode (enter the query manually) and simple mode (select table and columns). The help text and behavior is confusing and it will solve the issue with cursor moving.

**Comment by pivnicek** [comment]
Thanks @ondrejhlavacek for taking a look at this!  I'll deal with those exceptions above right away.

Regarding the query editor, I'm not encapsulating because each DB will differ in how they prefer that to happen I believe.  So putting the table and columns there is just a way of giving the user a head start.
As for 2-mode, that is how It currently behaves.  Once the query is edited manually the table and column selectors are cleared and disabled.  I guess you are thinking of having a switch (link, button or whatever) to switch between modes right?  Could be worth a try, I'll give it a go.  For existing queries I suppose they'd open in query mode.

Cheers dude

**Comment by pivnicek** [comment]
Issues:

- [ ] Autosuggest `value` prop not found on load
- [ ] No Connection should behave like no tables
- [ ] New Config error
- [ ] Weird Add Query button
- [ ] Spinner alignment
- [ ] Autosuggest as dropdown/select
- [ ] ? Simple/Advanced Switch

**Comment by Halama** [comment]
I will try it later but i am also for simple/advanced switch.

**Comment by pivnicek** [comment]
Great!  I'll shout out when I've fixed these listed issues

**Comment by pivnicek** [comment]
ok, the simple/advanced toggle seems to be working for me.  

One thing I've wanted to do for a long time is add some padding to that query editor so that the scroll bar doesn't make it difficult to read.  I've played with it a bit and from the code-mirror docs I see 
image
under styling.  I'd like to override that class here, but not sure quite how yet:)

**Comment by ondrejhlavacek** [comment]
Re: Encapsulation

It may be easy to parametrized/templated. It definitely should spit out a query that is valid for the selected RDMS. This config will fail and I didn't do anything wrong.

image

Re: Flip switch

That's quite nice! Few comments... I think seeing the query being built by clicking on table/columns would be nice. But I have this impression because it the Table/Column and Query fields are linked. When I switch to Query editing, the Table/Column inputs are still there and keep their values. When I switch back to Table/Column the Query keeps the value too (unless I make a change). Maybe if these two modes are distictively disconnected, it would make a bit more sense? I think it could be worth running through #uiux. It's a cool feature, and this will be a template for many other components (Salesforce Extractor is ready for this!), so it should be done right :-)

**Comment by ondrejhlavacek** [comment]
I don't fully understand the editor padding, is it something that bothers you in other CodeMirror instances in kbc-ui as well? Or only this use case? I have no scrollbars there, but that might be a feature of Apple's Magic Mouse!

**Comment by pivnicek** [comment]
cau @ondrejhlavacek Thanks for the comments!

I agree that the auto-formulated query should be valid.  So since I'm implementing the simple query creation in the backend anyways, it's rather straightforward to make it available as a synch action.

So I guess we have 2 options:
1) implement simpleQuery synch action and use that for auto-generated queries.
2) completely separate them (query editor will be blank or contain your last edits, selections won't change it)

**Comment by kacurez** [comment]
i'm looking at code and found this thing a bit strange:
https://github.com/keboola/kbc-ui/blob/89aaa1c4bd5d0ced2b26794be69cf25069bcbd04/src/scripts/modules/ex-db-generic/storeProvisioning.js#L244-L248
`loadSourceTables` is basically an action and flux doesn't permit dispatching an action during another action dispatch. Luckily here there is no direct flux action dispatch(only after promise gets resolved) so in 99,9% cases it won't raise an error. However we use `componentDidMount` approach for similar cases. So I would recommend to put `loadSourceTables` call in the `componentDidmount` of the QueryDetail page. It will behave identically but the solution si more "fluxible" here :)

**Comment by pivnicek** [comment]
Cheers @kacurez , I'll do that, thanks for the tip!

**Comment by pivnicek** [comment]
the elements aren't linked anymore, but I discovered an issue with new queries that it was sending `query: ""` but that should not be set

**Comment by pivnicek** [comment]
todo:

- [ ] In simple mode populate the primary key dropdown with columns, grouping source pks at the top
- [ ] group tables by schema in source tables dropdown
- [ ] add schema to config

**Comment by ondrejhlavacek** [comment]
Re: padding

I used these props

```
<CodeMirror
    ref="CodeMirror"
    value={this.props.queries}
    theme="solarized"
    lineNumbers={true}
    mode={resolveHighlightMode(this.props.backend, null)}
    lineWrapping={true}
    autofocus={true}
    onChange={this.handleChange}
    readOnly={this.props.disabled ? 'nocursor' : false}
    placeholder="CREATE VIEW transformed AS SELECT id FROM source;"
/>
```
and this css
```
.kbc-queries-editor textarea {
  resize: both;
  width: 100%;
  min-height: 300px
}
```
and I think there's no scrollbar.

Re: Synch action for query

I think a simple JS function might be enough, something along the lines

```
function (tableName, columnNames, stringEnclosure) {...}
```

I think it might be doable to store/pass the string enclosure somehow. Even if it's a code duplication (backend/frontend), it may not be worth sending a request and starting a docker container for each change in the config columns/tables.

---

Going to this config https://connection.keboola.com/admin/projects/232/extractors/keboola.ex-db-mysql/213874920/query/89877 yields an error

image

**Comment by pivnicek** [comment]
Thanks for the style tip @ondrejhlavacek , wrt to the autogenerated query just going to leave it for now. We can easily add it later.

**Comment by Halama** [comment]
It is working but i think it can be still improved.

- The form is still a bit messy - what about to separate it to `Add table` or `Add Query`?  Or discuss the flow with jack. Order of field also doesn't make sense. I want to select the table at first - so that primary key, name, and collumns will be prefilled.

Something like this
image

- In next version, db extractors should use default bucket. Now there is a same predefined bucket for all mysql extractors! Then we can get rid off that ouput table field or only table name can be changed but it will be prefilled.  It was a pain to configure this https://connection.keboola.com/admin/projects/258/extractors/keboola.ex-db-mysql/309089904
This is for separate issues, I just wanted to mention it.

**Comment by Halama** [comment]
I would leave there only one loader for the `Source table` with some text appending like `Fetching tables list from source database...`
image

btw. if I open directly new query page tables load is not triggered...

**Comment by pivnicek** [comment]
- [ ] handle errors on getTables request

**Comment by pivnicek** [comment]
https://github.com/keboola/kbc-ui/pull/1097/commits/7864aec1a49a3516e64a9cd3cbf940c4e8ad9c67 solves https://github.com/keboola/kbc-ui/issues/1112

**Comment by Halama** [comment]
Mrknu na to zas v pondeli..

**Comment by pivnicek** [comment]
70c4b5f solves https://github.com/keboola/kbc-ui/issues/1092

**Comment by Halama** [comment]
If I execute the query from queries list it throws error to console:
image

**Comment by Halama** [comment]
I am still not sure about the order of fields, but I can't say how to do it better.
Also static and editing views has completely different order of fields which is maybe confusing.
Also these gray values in static views are strange:
image
For increment statci value there should be ✅  or ❌

**Comment by pivnicek** [comment]
diky! mrknu na to

**Comment by pivnicek** [comment]
btw, @Halama the grey values will be in any static page that uses disabled input as display.  It's from the new kbc-bootstrap/indigo I think.

**Comment by Halama** [comment]
maybe we should get rid off the static page as we did for transformations...

**Comment by Halama** [comment]
cc @janmichek @ondrejhlavacek

**Comment by pivnicek** [comment]
I vote yes 👍 .  I'm just not sure how to indicate state wrt the save button, but I'm for getting rid of save and edit buttons too :-)

**Comment by Halama** [comment]
`indicate state wrt the save button` ? I think you should be able to detect the changes. And the behaviout would be same as transformation query edit. I know this will be huge amount of  coding in ex-db UI, but we should do editing more consistent.

**Comment by pivnicek** [comment]
ah, yes, that's how I imagined.  I'm very much for this approach in general. 
In the meantime I'll fix those other minor things above.  cheers!

**Comment by pivnicek** [comment]
I'll use jan's checkbox for incremental
image
I like it:)

**Comment by janmichek** [comment]
I am missing the context of 'getting rid of static pages'. A printscreen would be beneficial.
Unfortunately the component of checkbox is not production ready, yet. I know about browser issues, that needs to be solved.

**Comment by pivnicek** [comment]
ah, skoda.  ok, I'll stick with static icon then.

@janmichek , for reference, please run this branch and you can use project #2703 to try out any db-extractor.

**Comment by pivnicek** [comment]
Playing with the static page and I really want to get rid of it now:).  should be automatically in edit mode imho.

**Comment by Halama** [comment]
Yes, lets get rid off it now.

**Comment by Halama** [comment]
We should have the recommended edit behaviour desribed somewhere. Is it in Indigo UI?

**Comment by Halama** [comment]
There will be only issue with edit/link to the output table. But @ondrejhlavacek this already solved for CSV import:
image

**Comment by pivnicek** [comment]
ok, I'm going for it:)

**Comment by pivnicek** [comment]
I think there should be a `+ New Query` button in this sidebar too.
image

**Comment by janmichek** [comment]
So i have cloned your branch and went to your project, gone through few db extractors. I still don't know what do you want me to do with disabled fields / order of fields. 
The second issue - yes, lets put 'Editing mode' as a component to Indigo-ui

**Comment by pivnicek** [comment]
yeah, don't worry about that, I'm getting rid of the static detail page.  I think the order of elements in the form is pretty good, just not sure where best to put the incremental checkbox.

**Comment by Halama** [comment]
I think editing mode is more pattern than component.

Also it would be nice to remove static mode also from credentials:)

**Comment by Halama** [comment]
I was thinking about configuring new db extractor and I have one idea.
Add multiple table with one button with default settings, just open the modal with listed tables fetched from database (maybe with some metadata displayed like rows count and size) and check the tables which you want to fetch. Save and whole extractor is configured.

**Comment by pivnicek** [comment]
https://keboola.slack.com/archives/C02CFS0H3/p1505148807000599

**Comment by pivnicek** [comment]
Main tasks:

- [ ] Remove static details page
    - [ ] default as edit page, editMode init on form change
    - [ ] Reset form button
    - [ ] Save Query
    - [ ] Remember state of queries (ie. with query in edit mode, switich to different query and back and query should still be in edit mode with changes present.)
    - [ ] Update Name element to get the current editing value 
- [ ] Have new query use query detail form
- [ ] move credentials stuff to jsx
- [ ] switch credentials stuff be auto edit mode
- [ ] make quickstart method for new configurations

**Comment by ondrejhlavacek** [comment]
@janmichek is this https://github.com/keboola/kbc-ui/pull/1097#issuecomment-328475803 still unanswered? can provide screenshots/explanation.

**Comment by janmichek** [comment]
all good, solved

**Comment by pivnicek** [comment]
little things that need fixing:

New queries
- [ ] update isValid check for save enable
- [ ] add new editing query to side nav
- [ ] on reset remove editing query and nav to details page if new query
- [ ] fix default tableName behaviour
- [ ] add edit tableName icon/state
- [ ] add help text

Quickstart
- [ ] fix table select input
- [ ] validate tables creations
- [ ] add help text

**Comment by pivnicek** [comment]
Here's the quickstart in action...
db-ex-quickstart

**Comment by pivnicek** [comment]
There remain some issues here unfortunately, here is my list:

Quickstart:
- [ ] The selection isn't removed from the dropdown when selected.
- [ ] Tables with PKs should default to `incremental` imho

Main form
- [ ] default table name component is broken

New Query
- [ ] loading the page to new-query URL breaks the side nav
- [ ] reset of new query should result in empty form, not nav to index

Error Handling
- [ ] It would be great to show connection status on the index page
- [ ] Index and form page should both show any http errors.

**Comment by ujovlado** [comment]
Hm, I checked out a this is what I have after creating new configuration:
screenshot_2017-10-06_16-48-25

- why that error? (it appeared after few seconds) I didn't touch anything
- "new query" button position looks a bit random
- also, should "new query" be there if I didn't configure anything?
- there's missing "divider" between main content and sidebar (it's probably becasuse broken layout.)

**Comment by Halama** [comment]
- the new query button shouldn't be there if the credentials are not set. 
- the new query button should't be there when no queries are set imho, it is very ugly
- whole layout is somehow broken and not consistent with other components
WTF:
image

It should look like this:
image

hmm, I've just noticed ujos comment :)

**Comment by Halama** [comment]
but, the query/table detail page looks great 👍

**Comment by Halama** [comment]
I've just found a strange behaviour, it looks like the list on query detail page is grouped by name instead of id.
oct-08-2017 13-37-37

**Comment by ujovlado** [comment]
I fixed few issues and found other:

- Replace `var` by `const, let` in `QueryDeleteButton.jsx`
- Don't allow same query name (but allow same table) when defining new query
- Add "Database" prefix to database, otherwise I don't know what is database and what is table (see image bellow)

selection_002


- Disable "Let's go" button until I select at least one table (prevents err)

**Comment by pivnicek** [comment]
Thanks guys!  Should have this ready end of day today.

**Comment by ondrejhlavacek** [comment]
Let me know when everything is ready, I'd like to set my pair of fresh eyes on that too! Thanks!

**Comment by pivnicek** [comment]
@ondrejhlavacek Feel free to give it a test drive ;-).  I've updated as per the above feedback, just need to add the unique name validation mentioned by ujo, but otherwise ✅

**Comment by ondrejhlavacek** [comment]
@pivnicek can you give me a rough guide to where has something changed? so i can focus on the areas.

**Comment by pivnicek** [comment]
Sure,

Since you last looked, 
* the credentials section has been updated to jsx reset/save workflow
* there is a quickstart table selection for automatic config generation for new configs
* the main form has been updated
So almost everything :-).  There are 2 flows,  supported components (mysql, pgsql ... etc) have the table selection,  and non-supported components (firebird, impala, custom one-off extractors) which do not have table selections.
I was thinking it could be possible for us to use the 2nd flow as an initial default and the 1st one as a user-flag feature if we wanted to.
Cheers

**Comment by pivnicek** [comment]
- [ ] Reset doesn't work on query element.

**Comment by ondrejhlavacek** [comment]
I'll just spit here some random comments. Some may be more relevant than others, some may be added in a later iteration?

### 1) Reload

This should be reloaded with a button/link, not with reloading the whole page.

image

### 2) Helper Texts

I don't think we use similar format (centered text, centered form) in other places?

image

The help text can be simply a `help-block` to the input element, they can contain rich content, like here

image

### 3) Minor typo

image

I guess it should say `Connecting...` without the extra space.

### 4) Error message

image

The first line has incorrect grammar :-)

### 5) Table selector

image

Is the `sys` schema required? (It's a RDS). I guess the extractor sync call should filter out these.

The drop-down is a pixel or two wider than the input.

### 6) Initialize configs button

image

Maybe a plain `Create` would be enough? I'd still consider reformatting the whole form/dialog a bit.

### 7) Default destination

image

All of my MySQL extractors point to the `in.c-keboola-ex-db-mysql` bucket. I don't think being able to select bucket is necessary, just the table name? This is how S3 extractor deals with it after opening the edit mode

image

### 8) Advanced mode checkbox

It should have the explaining help-block similar to `Incremental Load` instead of explaining after a colon.

image

### 9) Advanced mode switch

I have to press the checkbox twice every time to switch the mode (both ways). The first click in the simple mode removes the primary key setting (and displays a warning sign next to the row name in the row selector), the second click finally switches to the advanced mode. 

Clicking on Reset in advanced mode, when a simple mode state is saved, does not revert the UI back to the simple mode.

image

(posting this partial comment now to avoid loss :-) will keep updating this comment for a while)

**Comment by Halama** [comment]
Ta default desitnation je asi na dalsi issue, protoze db ex zatim nepodporuje defaultBucket. Kazdoapdne to pak musi zmizet protoze takhle je to pekelny.

**Comment by pivnicek** [comment]
Thanks for the comments @ondrejhlavacek 

@Halama Yeah, I was thinking about the default bucket, but we'll need to elegantly support old configurations, so I agree -> next iteration.

**Comment by pivnicek** [comment]
phew!  ok @ondrejhlavacek , here's my thoughts:

### 1) Will do
### 2) done -- (the setup credentials button is also centered)
### 3) lol, sure, will do.
### 4) done, omg
### 5) This would be an issue for whichever backend.  were you using mysql?
### 6) done
### 7) Future iteration will use default bucket -- so maybe on hold.
### 8) done
### 9) fixed
### 10) Will do, thanks for the suggestion
### 11) Feature :-)  not sure yet if will do
### 12) I think I know what you mean and mostly agree.  Just not sure if it should go in a next iteration or not.  It would be a fairly big change.  Let's chat about it later:)
### 13) Yes, this is leftover from the old one,  and I agree that the action buttons should probably be more identified with the row.  If we do #12, that should solve this as a side-effect.
###  14) Will do
### 15) Will make each click create a new row, agreed.  Also will fix reset.  regarding position/style,  maybe we can take it to #uiux.
### 16) I'm also not sure:)
### 17) Yes, totally.  we can add that when we have #19  done
### 18) This is a shared component,  (RunComponentButton) I will look into it.
### 19)  Absolutely!

**Comment by ondrejhlavacek** [comment]
I just realized one thing. I got too carried away by config rows I'm working on right now and didn't realize this has nothing to do with actual config rows. Visually it's a similar thing, but some of that not at all (rows order #17, code abstraction #19). I will do this all when it's my turn with config rows and I will probably want to solve the view modes (#12) as well, so no need to care about it. Will take this as a visual guideline and will take care of processing the UX and the code abstraction properly :-)

**Comment by pivnicek** [comment]
yeah, I agree with you about that, but I also think that ideally the extractors would use config rows for their individual extraction definitions also,  but we can work towards that harmony :).

**Comment by pivnicek** [comment]
Gents (@ondrejhlavacek @Halama @ujovlado),

This has now been updated to according to the above comments.

**Comment by ujovlado** [comment]
@pivnicek just one question:
selection_003

^ we refer here to database as "schema", but in credentials setup it's a database. Shouldn't be here "database" too?

**Comment by pivnicek** [comment]
@ujovlado It kind of depends on the backend.  Normally it is `Database`/`Schema`/`Table`.  The value in the dropdown should be schema and in the credentials it should refer to database.

**Comment by ujovlado** [comment]
@pivnicek  Ok, thanks for clarification :) I'm ok with that since as you said there'll be only  one value.

**Comment by ujovlado** [comment]
@pivnicek can you also check this?

https://github.com/keboola/kbc-ui/pull/1097/files#diff-3af743b540daae7adcf188f198b402faR273, looks like quickstart it's not working.

**Comment by pivnicek** [comment]
omg!  thanks, fixing it now

**Comment by ujovlado** [comment]
Anyway, I would prefer extract `componentSupportsSimpleSetup` somewhere else, pass it `componentId` and that's it. After that just require function where it's needed - it's king of magic like this :)

**Comment by pivnicek** [comment]
j, souhlas, exactly what I'm doing:)  dik!

**Comment by pivnicek** [comment]
ok, that should be better now.

I noticed that the delete button on the index page is behaving "oddly".  Working on that now, must be side effect of me removing the confirm dialog.

**Comment by ujovlado** [comment]
@pivnicek sorry, I didn't write all at once, but I found another glitch, Disabled save button:
screenshot_2017-10-11_14-34-27

**Comment by pivnicek** [comment]
@ujovlado how did you do that?

**Comment by ujovlado** [comment]
> how did you do that?
Autoconfigured new MySQL extractor and tried to add new table.

**Comment by pivnicek** [comment]
Hmm, I haven't been able to reproduce that, but I noticed that deleting new query isn't working now :-/

**Comment by ujovlado** [comment]
@pivnicek I'll record it.

**Comment by ujovlado** [comment]
I tried to edit as much as I can, but button is still disabled:
peek 2017-10-11 15-16

**Comment by pivnicek** [comment]
Ah, I see! thanks ujo.  btw, please pull the latest fixes ;-)

**Comment by ujovlado** [comment]
Yeah, I have pull runnig in watch mode :)

**Comment by ujovlado** [comment]
Oh fuck, the hard refresh helped. My fault, sorry.

**Comment by pivnicek** [comment]
not at all,  I'm still thinking about how to indicate the requirement

**Comment by Halama** [comment]
Few notes:

## 1 - the layout is still broken
image

There are some ugly paddings near the rows list, also line below search is missing. Please check other extractor/writers. 

It should look like this:
image

## 2 - Destination hint
I think the mention of empty default value doest not make sense anymore there.
image

## 3 - Credentials save
What about to automatically redirect to tables list page after save?

**Comment by pivnicek** [comment]
> What about to automatically redirect to tables list page after save?
yes!

**Comment by ujovlado** [comment]
@pivnicek hopefully, one of the latest changes: the `key` prop in left column (listing queries) should be unique:
screenshot_2017-10-11_15-34-17
^ This happens during saving and it's logging errors until "rerender" is done.

**Comment by ujovlado** [comment]
I found another small issues :)

- New Query should be added to the top of the list every time (in query detail click "Create a new query") ... now it's based on what query id it gets.
- Switching between advanced/normal mode causes an error (something with state in query editor)

**Comment by pivnicek** [comment]
Ah, that nav position issue is interesting, I'll need to think it over:)

**Comment by ujovlado** [comment]
> Ah, that nav position issue is interesting, I'll need to think it over:)

You can create a new store item holding ids of new queries and every time new query is created `unshift` value (query id) to this store item. Then in navigation, you can sort new queries by the newly created store item.

**Comment by ujovlado** [comment]
Clearing "Source Table" value (clicking x, or pressing Esc) causes error:
screenshot_2017-10-11_23-10-18

**Comment by ujovlado** [comment]
> You can create a new store item holding ids of new queries and every time new query is created unshift value (query id) to this store item - so new query will appear at the beginning. Then in navigation, you can sort new queries by that store item.

@pivnicek I can help with this if you want

**Comment by pivnicek** [comment]
@ujovlado be my guest! <3.  I'm not completely satisfied with that QueryNav.jsx rows method, it's pretty hacky imho :-).

**Comment by pivnicek** [comment]
Zatim I'll fix that clear table select error

**Comment by pivnicek** [comment]
nice ujo, thanks alot for that

**Comment by ujovlado** [comment]
> nice ujo, thanks alot for that

I did it all yesterday while playing with it. Almost. :stuck_out_tongue:

**Comment by ujovlado** [comment]
Ok, another thing I will check is MongoDB ext. It's a bit broken. I hate how I did it and how it's connected to ex-db-generic.

**Comment by pivnicek** [comment]
Yeah, I think sharing credentials stuff is alright, but RDBs and Document stores can't really share query formulations.

**Comment by ujovlado** [comment]
That mongodb<->db-generic is example how copying is better that bad abstraction. I saved few files, but it's complicated as hell.

Ok, part 1 done. I see the "Save" credentials button is disabled all the time, can you check it?

**Comment by pivnicek** [comment]
ok @ujovlado I fixed the mongodb credentials editing.  Sorry I missed that, should have done it earlier, thanks for checking

**Comment by ujovlado** [comment]
I'm going to check all the extractors again, I will let you know if there are any problems.

**Comment by pivnicek** [comment]
@ujovlado thanks!  fyi I have a known issue with the sample db2 backend I'm using for testing.  I'm still trying to figure out how to solve it :-/.

**Comment by ujovlado** [comment]
I did a fresh rebase, hopefully I'll finish review tomorrow.

**Comment by ujovlado** [comment]
@pivnicek another glitch in mongodb (when creating new export)

screenshot_2017-10-31_22-26-00

**Comment by ujovlado** [comment]
^ looks like there's a dispatch, which wasn't there before and it is trying to save new query:
`dispatch INSTALLED_COMPONENTS_LOCAL_STATE_UPDATE (2) ["newQueries", "isSaving"]`

**Comment by ujovlado** [comment]
^ Fixed

**Comment by padak** [comment]
Pokud zaškrtnu "Encrypted Connection" u credentials MySQL, nejde to odškrtnout. Nemám-li ale SSL klíče, tak předpokládám, že to bude při spojení sypat errory. 

A v popisech input fieldů jsou divně středníky:
image

**Comment by ondrejhlavacek** [comment]
Received this 
image

in https://connection.keboola.com/admin/projects/578/jobs/327829064?q=

config http://localhost:3000/?token=578-***#/extractors/keboola.ex-db-mysql/262188348/query/88971

**Comment by ondrejhlavacek** [comment]
image

**Comment by ondrejhlavacek** [comment]
image

the generate link does not sit at the same baseline. maybe a button would be better? idk!

**Comment by ondrejhlavacek** [comment]
image

the copy button should not be inside the text area (but next to the field label?), regenerate button

**Comment by ondrejhlavacek** [comment]
image

Help may be on a line below and could be a whole sentence like "See the documentation for more details" or so

**Comment by ujovlado** [comment]
> the copy button should not be inside the text area (but next to the field label?), regenerate button
It's not a `textarea`, it's a `pre` element. I vote for consistency here and leave it as is. For example, authorization looks the same.

screenshot_2017-11-01_09-13-59

What we can do is add text "Copy public key to clipboard".

**Comment by ondrejhlavacek** [comment]
Does it need to be inside the `pre` element? I'm in for keeping the consitency, but it should be formatted the same way as the content.

**Comment by ujovlado** [comment]
Maybe ... let's fix it in separate issue after this PR is merged. #1245

**Comment by pivnicek** [comment]
Thanks @ondrejhlavacek !  the above error and warnings are fixed now.

**Comment by odinuv** [comment]
confusing wording here 
image

it speaks about tables, so the "there are no queries" is weird

**Comment by odinuv** [comment]
image

click "new query", don't do anything, go back, click "new query" - an untitled item is created which is not shown on the main screen

**Comment by pivnicek** [comment]
Thanks, I also didn't like that it said query everywhere, changed to table now.

As for your second one (the index page nav being different from the detail page nav), we discussed this above, and decided to add it in a follow-up PR.  I don't believe it's a very big change, so I'm very tempted to do it now :-).  but either way, it will happen soon.

**Comment by odinuv** [comment]
[2017-11-01 13:12:28] ex-db-snowflake.ERROR: Unrecognized option "advancedMode" under "parameters.tables.0" [] []
-> when running a single query from query detail (`/extractors/keboola.ex-db-snowflake/327861583/query/55510`), works from the main page

**Comment by pivnicek** [comment]
@odinuv please pull, that was fixed ^^

**Comment by odinuv** [comment]
`Output mapping does not match destination table: primary key '' does not match 'Id' in 'in.c-keboola-ex-db-snowflake.USER'.
ExceptionId docker-ab71df9aab6c92e1007c7a0b7bc2b98c`

to reproduce:
- add table
- add PK
- run
- remove table
- add table
-> it now says "Cannot add column" (because the table exists) - it should either load them from existing table or let me add them, otherwise i can't import to existing table having pk

**Comment by pivnicek** [comment]
ah,  it gets the PK from the source column.  It should look at the destination table too.  Cheers.

**Comment by Halama** [comment]
What is the current status? are all known issues cleared? Can I test it?

**Comment by pivnicek** [comment]
@Halama Yes, all known issues are closed.  We've decided to address the inconsistency between the index list and detail sidebar list in a follow-up PR.

**Comment by ondrejhlavacek** [comment]
@pivnicek (i've mentioned this earlier, but opakování is matka moudrosti) I've discussed this with Jack and Jan and will try to address it in the new version of S3 extractor, so we can discuss it there. It should be 100% applicable.

**Comment by ujovlado** [comment]
@pivnicek the last of the mohicans, single query run (config data).

This is my config:
```
enabled:true
id:45998
incremental:false
name:"test3"
outputTable:"in.c-keboola-ex-db-redshift.test3"
primaryKey:[]
query:"SELECT * FROM "test""
```
^ the query is in advanced mode

but there's no advanced mode property, so single query run will fail, because this code will delete `query`:

```js
if (runQuery.get('advancedMode')) {
        runQuery = runQuery.delete('table');
        runQuery = runQuery.delete('columns');
      } else {
        runQuery = runQuery.delete('query');
      }
```
shouldn't  we assume advanced mode by `query` property?

```js
if (runQuery.get('query')) {
        runQuery = runQuery.delete('table');
        runQuery = runQuery.delete('columns');
      } else {
        runQuery = runQuery.delete('query');
      }
```

**Comment by ujovlado** [comment]
^ it's on query list page (not in detail)

screenshot_2017-11-09_18-39-01

I think we only need to "simulate" that advanced mode (or get rid of it).

**Comment by pivnicek** [comment]
@ujovlado it should be sufficient to wrap
```
if (runQuery.get('advancedMode')) {
        runQuery = runQuery.delete('table');
        runQuery = runQuery.delete('columns');
      } else {
        runQuery = runQuery.delete('query');
      }
```
In `if (isEditingQuery(runQuery.get('id'))`

**Comment by ujovlado** [comment]
Hm, I think I don't understand. Why to wrap to "isEditing". It's not about editing. All queries are saved properly (nothing as draft, etc.).

**Comment by pivnicek** [comment]
Only editing queries have the `advancedMode` property.  Saved queries, like those on the index page are already cleaned and have either table or query but never both.

**Comment by pivnicek** [comment]
This was added originally to make running editing queries work.

**Comment by ujovlado** [comment]
@pivnicek I changed it a bit ... as I mentioned (and didn't understand), the queries are already saved. there's no "editing" present. So I added simple "source" parameter to that fn.

**Comment by ujovlado** [comment]
Idem to teda mergnut :tada:

**Pull request merged**
