### PR TITLE
OAuth v3 + migration public release

### PR DESCRIPTION
**Pull request by MiroCillik**
Fixes https://github.com/keboola/kbc-ui/issues/2841

Proposed changes:
- remove conditions for feature `oauth-migration`
- remove conditions for feature `oauth-v3`

All new oauth configurations will be created with version 3.
All users/projects will see migration/deprecation warning on their overview pages.

### CODE REVIEW

**Comment by MiroCillik** [comment]
Merge this PR alongside post on status: http://status.keboola.com/migrate-to-new-version-of-oauth-broker-api?draft=eu0wcMf4aGBaChxW8OajPBGTIoivFVOCNsiTVHrsfRA=

**Comment by MiroCillik** [comment]
Este mam pripraveny potom link na status, mam ho tam pridat rovno? A ked sa to mergne, tak hned ten status vypublikovat tiez?

**Comment by ujovlado** [comment]
A rebase nic? :)

**Comment by MiroCillik** [comment]
Som pouzil to tlacitko v GitHub UI :D Sorry, myslel som si naivne, ze to
spravi rebase..

**Pull request merged**
