### PR TITLE
Add "back button" to return to the "list of tables"

### LINKED ISSUE #916: back navigation from writer credentials page
After you make credentials for your writer, there is no obvious navigation to continue setting up your config

pasted image at 2017_04_06 12_58

### LINKED ISSUE #1112: Db extractors - test credentials disabled in static screen
Proč je ve statickém režimu tlačítok test credentials deaktivované?
Mělo by být aktivované pokud jsou credentials zadané. Stejně to funguje u db writerů.
image

### PR DESCRIPTION
**Pull request by ujovlado**
Fixes #916 
Fixes #1112

### CODE REVIEW

**Comment by ujovlado** [comment]
Trosku som sa v tom zavrtal, vo writeroch a extractoroch sa to sprava dost odlisne - niekde mozem testovat credentials, niekde nie - a pritom mam podobny setup. Bude to chciet doladit.

**Comment by ujovlado** [comment]
Trosku som vylepsil loader:
screenshot_2017-09-22_22-30-33

A ked editujem, tak ma to upozorni aby som nezabudol ulozit:
screenshot_2017-09-22_22-33-20

**Comment by pivnicek** [comment]
Why don't we have a save button down there that also works as "going back"?

**Comment by ujovlado** [comment]
@pivnicek I don't know why - someone designed it that way - save button in top right corner, which will redirect you back to the list of tables.

**Comment by ujovlado** [comment]
Anyway, I think it's not good idea (right now) to add another save button down - under the form. Maybe in next iteration when all forms are unified.

**Comment by pivnicek** [comment]
ok, just thought the new button could be "Save and return" or something.  But we can solve it if we want to in #1097

**Comment by ujovlado** [comment]
@pivnicek there is already ~100 commits there (in #1097) ... It's starting to be a bit scary, I will prefer not to add more features there, because we'll end up with PR which is going to change everything :-D

**Comment by pivnicek** [comment]
yes, it is practically a complete re-write of db-ex-generic.  We can continue discussion there maybe.

**Comment by ujovlado** [comment]
Sure, we can ... I only wanted to fix these 2 issues - I'm not going to change more parts here (in ex db generic) until that big PR is done. ;)

**Pull request merged**
