### PR TITLE
Events Table - prevent break created and component column

### PR DESCRIPTION
**Pull request by natocTo**
Před:
pred

Po:
po

### CODE REVIEW

**Comment by kacurez** [comment]
@ujovlado nerozumiem co tym myslis?

**Comment by ujovlado** [comment]
No, ze ked davas merge, nechaj tam ten merge commit ... potom sa to lepsie hlada revertuje ;)

**Comment by kacurez** [comment]
aha, ja to mergujem z githubu, takze v podstate nemam klikat na `rebase and merge` ale na `create merge commit`? :)

**Comment by ujovlado** [comment]
Jo, "Create a merge commit" ... kuknem ci sa to neda vynutit.

**Comment by ujovlado** [comment]
Setupol som to :)

screenshot_2018-11-06_11-56-29

**Comment by kacurez** [comment]
moderato 👍

**Pull request merged**
